logging_level: INFO
solve_network: solve  #'solve' or 'skip'

results_dir: 'results'
costs_dir: '../technology-data/outputs'

# from ../pypsa-eur-sec/results/<run>/prenetworks-brownfield
n_2025: 'input/v6_elec_s_37_lv1.0__3H-B-solar+p3_2025.nc'
n_2030: 'input/v6_elec_s_37_lv1.0__3H-B-solar+p3_2030.nc'


###################
# Scenario controls

run: 'test'

#wildcards
scenario:
  policy:  ["res100", "ref", "res100", "cfe80", "cfe85", "cfe90", "cfe95", "cfe98", "cfe99", "cfe100"]
  palette: [ "p1", # onwind + solar + battery 
             "p2", # onwind + solar + battery + LDES
             "p3", # onwind + solar + battery + LDES + clean dispatchable gen
            ]
  zone: [ "IE",
          "DK",
          "DE",
          "NL"
        ]
  year: ['2030', 
         '2030'
         ] # controls both the brownfield fleet and tech costs projection
  participation: ['10', 
                  '25'
                  ] #share [%] of CI load per zone following 247-CFE approach

#data center
ci:
  name: "google"
  profile_shape: "baseload" #"baseload", "datacenter", "industry"
  res_techs: ["onwind","solar"]

#regional coverage of the model: "regions" or "EU"
  #"regions" -> strips the model to country where CI load is located + all neighboring countries 
  #"EU" -> keeps the whole European power system (full ENTSO-E area)
area: "EU"


###################
# Fixed settings

node_suffixes_to_keep: ["H2","battery"] #"low voltage","home battery"]                            
carrier_to_keep: [ #generators
                  "offwind","offwind-ac","offwind-dc","solar", "onwind","ror", #"solar rooftop",
                  #storage units
                  "PHS","hydro", 
                  #lines, links
                  "AC", "DC", 
                  #links
                  "nuclear", "uranium", "gas","OCGT","CCGT","oil", "lignite", "coal",
                  "H2 Electrolysis","H2 Fuel Cell","H2 pipeline",
                  "battery charger","battery discharger", #"home battery charger","home battery discharger",
                  "urban central solid biomass CHP", #"electricity distribution grid",
                  #Stores
                  "H2 Store","co2","co2 stored","battery", "solid biomass", #"home battery"
                  #Loads ('industry electricity' is included)
                  "electricity"  
                    ]  
additional_nodes: ["EU oil","EU gas", "EU lignite", "EU coal", "EU uranium", "EU solid biomass", "co2 atmosphere","co2 stored"]


global:
  policy_type: "co2 price" # one of ["co2 cap", "co2 price"]
  co2_baseline: 1.2e+7  #MtCO2/a - rough "energy industries" emissions in 1990 and 2020 in IE: 1.2e7
  co2_share: 0.5 #pu  - rough target for 2030
  limit_res_exp_2025: 2 #max ratio (to 2021 basis) of renewable tech expantion per zone and technology 
  limit_res_exp_2030: 4 #max ratio (to 2021 basis) of renewable tech expantion per zone and technology 
  co2_price_2025: 80 #EUR/tCO2
  co2_price_2030: 130 #EUR/tCO2
  grid_res_techs: ["offwind","offwind-ac","offwind-dc","onwind", "ror", "solar", 
                    "hydro","urban central solid biomass CHP"] #"solar rooftop"
  grid_clean_techs: ["offwind","offwind-ac","offwind-dc","onwind", "ror", "solar",
                    "hydro", "nuclear", "urban central solid biomass CHP"] #"solar rooftop"
  emitters: ["CCGT", "OCGT", "coal", "lignite", "oil"]


costs:
  lifetime: 25 #default lifetime
  discountrate: 0.07  # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  USD2013_to_EUR2013: 0.7532 # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html # noqa: E501
  USD2021_to_EUR2021: 0.8460 # [EUR/USD] ECB
  adv_nuclear_overnight: 7138 # 2021$/kW CAPEX https://www.eia.gov/outlooks/aeo/ 2022
  price_green_hydrogen: 3 #EUR/kg
  price_lignite: 6.5 # EUR/MWhth from TYNDP2020 -> default is 2.9
  price_coal: 8.9 # EUR/MWhth from TYNDP2020 -> default is 8.15
  price_gas: 35 # EUR/MWhth -> https://energy.ec.europa.eu/system/files/2022-05/SWD_2022_230_1_EN_autre_document_travail_service_part1_v3.pdf
  adv_geo_overnight_2025: 10000 # 2022$/kW CAPEX
  adv_geo_overnight_2030: 10000  # 2022$/kW CAPEX
  allam_ccs_overnight_2025: 2760 # 2022$/kW CAPEX, 2300*1.2
  allam_ccs_overnight_2030: 2600 # 2022$/kW CAPEX, 2300*1.2 (!)
  # price_gas_2025: 50.0 # https://www.powernext.com/futures-market-data
  # price_oil = 50.0 # EUR/MWhth -> TYNDP2020 = default 
  # price_uranium = 1.7 EUR/MWhth -> TYNDP2020  is 2.6
  # TYNDP2020: https://2022.entsos-tyndp-scenarios.eu/download/

#~size of C&I electricity load per country
#https://ec.europa.eu/eurostat/databrowser/view/ten00129/default/table?lang=en
#https://ec.europa.eu/eurostat/databrowser/view/ten00128/default/table?lang=en
ci_load: 
  IE: 2200.
  DK: 2240.
  DE: 38410.
  NL: 8140.


#national policies
#countries with nuclear phase-out policy (FR and BE shifted plan to 2035)
#source: https://world-nuclear.org/
nodes_with_nucsban: ["DE1 0"]
#countries with coal phase-out policy before 2025 and 2030
#countries with the plan year 2025 + 'DE' are in the 2030 bracket
#source: https://beyond-coal.eu/europes-coal-exit/
policy_2025: ['BE', 'SE', 'PT', 'AT', 'FR', 'GB']
policy_2030: ['BE', 'SE', 'PT', 'AT', 'FR', 'GB', 'IT', 'IE', 'HU', 'MK', 'DK', 'GR', 'NL', 'FI', 'RS', 'ES', 'SK', 'DE']
#source: https://ec.europa.eu/info/energy-climate-change-environment/implementation-eu-countries
#data for NL is dummy
res_target_2025:
  IE: 0.47
  DK: 0.9
  DE: 0.45
  NL: 0.35
res_target_2030:
  IE: 0.7
  DK: 1.1
  DE: 0.8
  NL: 0.5


solving:
  #tmpdir: "path/to/tmp"
  options:
    formulation: kirchhoff
    n_iterations: 2  #iterations with CFE factor
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-6
    Seed: 123
    AggFill: 0
    PreDual: 0 
    GURO_PAR_BARDENSETHRESH: 200


tech_colors:
  #CI
  "local": "#b474b4"
  "PPA": "#b474b4"
  "grid": "#9ccc65"
  "grid imports": "#9ccc65"
  "revenue": "g"
  # RES
  "wind": "#74c6f2"
  "offshore wind": "#6895dd"
  "onshore wind": "#74c6f2"
  "solar": "#ffef60"
  "solar rooftop": '#000000'
  # Clean Dispatchable
  "advanced nuclear": "#df3439"
  "advanced geothermal": "#99582a"
  "advanced dispatchable": "#99582a"
  "NG-Allam": "#540b0e"
  'hydroelectricity': '#298c81'
  'nuclear': '#ff8c00'
  # Storage
  "battery": "#666666"
  "battery inverter": "#444444"
  "battery storage": "#666666"
  "hydrogen storage": "#990090"
  "hydrogen fuel cell": "#990090"
  "hydrogen electrolysis": "#550055"
  'pumped hydro storage': '#51dbcc'
  # Emitters
  "OCGT": "#d35050"
  "CCGT": "#b20101"
  "Gas OC": "#d35050"
  'hard coal': '#545454'
  'lignite': '#826837'
  'oil': "#808080"
  # biomass
  'solid biomass': '#baa741'
  # power transmission
  "lines": '#6c9459'
  "transmission lines": '#6c9459'
  "electricity distribution grid": '#97ad8c'